@rootUrl = http://localhost:8000/api/v1/auth

###
POST {{rootUrl}}/register
Content-Type: application/json

{
    "fName" : "prash",
    "lName" : "shrestha",
    "email" : "shresthaprashrijan@gmail.com",
    "phone" : "123456789",
    "password": "prashrijan",
    "confirmPassword": "prashrijan"
}

###login user
POST {{rootUrl}}/login
Content-Type: application/json

{
    "email" : "shresthaprashrijan@gmail.com",
    "password": "prashrijan"
}


###
GET {{rootUrl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNocmVzdGhhcHJhc2hyaWphbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzk4NDAyODgsImV4cCI6MTczOTkyNjY4OH0.pabvCd8L_NkLUyQklsBhWrELHRNhuxigEjkhpJoLLnQ