const books = [
    {
        title: "Clean Code",
        author: "Robert C. Martin",
        isbn: "978-0132350884",
        publishedYear: 2008,
        thumbnail:
            "https://m.media-amazon.com/images/I/51b7XbfMIIL._SL500_.jpg",
        description: "A Handbook of Agile Software Craftsmanship.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.7,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "clean-code",
    },
    {
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt, David Thomas",
        isbn: "978-0201616224",
        publishedYear: 1999,
        thumbnail:
            "https://m.media-amazon.com/images/I/41as+WafrFL._SL500_.jpg",
        description: "Your journey to mastery.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.8,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "pragmatic-programmer",
    },
    {
        title: "You Don't Know JS",
        author: "Kyle Simpson",
        isbn: "978-1491904244",
        publishedYear: 2014,
        thumbnail:
            "https://m.media-amazon.com/images/I/71GsZGf3opL._UF894,1000_QL80_.jpg",
        description: "Deep dive into JavaScript.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.6,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "you-dont-know-js",
    },
    {
        title: "Eloquent JavaScript",
        author: "Marijn Haverbeke",
        isbn: "978-1593279509",
        publishedYear: 2018,
        thumbnail: "https://eloquentjavascript.net/img/cover.jpg",
        description: "A modern introduction to programming.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.5,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "eloquent-javascript",
    },
    {
        title: "Python Crash Course",
        author: "Eric Matthes",
        isbn: "978-1593279288",
        publishedYear: 2015,
        thumbnail: "https://m.media-amazon.com/images/I/81ZBWeKoZVL.jpg",
        description: "A hands-on, project-based introduction to Python.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.7,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "python-crash-course",
    },
    {
        title: "Design Patterns",
        author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        isbn: "978-0201633610",
        publishedYear: 1994,
        thumbnail:
            "https://m.media-amazon.com/images/I/51nL96Abi1L._UF894,1000_QL80_.jpg",
        description: "Elements of Reusable Object-Oriented Software.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.7,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "design-patterns",
    },
    {
        title: "Code Complete",
        author: "Steve McConnell",
        isbn: "978-0735619678",
        publishedYear: 2004,
        thumbnail: "https://m.media-amazon.com/images/I/61GzazUmKyL.jpg",
        description: "A practical handbook of software construction.",
        isAvailable: "Active",
        expectedAvailable: null,
        averageRating: 4.7,
        genre: "Programming",
        addedBy: { name: "Admin One" },
        lastUpdatedBy: { name: "Editor One" },
        slug: "code-complete",
    },
];

export default books;
